# Generated by Django 5.0.6 on 2024-06-01 15:18

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='date',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='id',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='is_delivered',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='item',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='location',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='delivery',
            name='barangay',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='delivery',
            name='city',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='delivery',
            name='company',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='delivery',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='N/A', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='delivery',
            name='country',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='delivery',
            name='email_address',
            field=models.EmailField(default='N/A', max_length=254),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pk_logistics_id',
            field=models.AutoField(primary_key=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='province',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='delivery',
            name='street',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='delivery',
            name='zip_code',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
