# Generated by Django 5.0.4 on 2024-06-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_delete_customer_remove_delivery_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='pk_logistics_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
