# Generated by Django 5.0.4 on 2024-06-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_delivery_pk_logistics_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reorder_point',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='item',
            name='reorder_status',
            field=models.CharField(default='OK', max_length=10),
        ),
    ]
