# Generated by Django 5.0.4 on 2024-05-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer'),
    ]

    operations = [
        # Comment out or remove the AddField operation for 'barangay'
        # migrations.AddField(
        #     model_name='customer',
        #     name='barangay',
        #     field=models.CharField(default='', max_length=255),
        # ),
        # Comment out or remove the AddField operation for 'city'
        # migrations.AddField(
        #     model_name='customer',
        #     name='city',
        #     field=models.CharField(default='', max_length=255),
        # ),
        # Comment out or remove the AddField operation for 'country'
        # migrations.AddField(
        #     model_name='customer',
        #     name='country',
        #     field=models.CharField(default='', max_length=255),
        # ),
        # Comment out or remove the AddField operation for 'email_address'
        # migrations.AddField(
        #     model_name='customer',
        #     name='email_address',
        #     field=models.EmailField(default='', max_length=254),
        # ),
        # Comment out or remove the AddField operation for 'first_name'
        # migrations.AddField(
        #     model_name='customer',
        #     name='first_name',
        #     field=models.CharField(default='', max_length=255),
        # ),
        # Comment out or remove the AddField operation for 'last_name'
        # migrations.AddField(
        #     model_name='customer',
        #     name='last_name',
        #     field=models.CharField(default='', max_length=255),
        # ),
        # Comment out or remove the AddField operation for 'province'
        # migrations.AddField(
        #     model_name='customer',
        #     name='province',
        #     field=models.CharField(default='', max_length=255),
        # ),
        # Comment out or remove the AddField operation for 'street'
        # migrations.AddField(
        #     model_name='customer',
        #     name='street',
        #     field=models.CharField(default='', max_length=255),
        # ),
        # Comment out or remove the AddField operation for 'zip_code'
        # migrations.AddField(
        #     model_name='customer',
        #     name='zip_code',
        #     field=models.CharField(default='', max_length=20),
        # ),
        # The AlterField operation for the 'phone_number' field is removed
        # migrations.AlterField(
        #     model_name='customer',
        #     name='phone_number',
        #     field=models.CharField(default='', max_length=15),
        # ),
    ]
