# Generated by Django 5.0.4 on 2024-05-29 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_id_customer_customer_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['customer_id']},
        ),
    ]
