# Generated by Django 5.0.6 on 2024-06-01 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_barangay_customer_city_customer_company_and_more'),
        ('accounts', '0007_alter_customer_options'),
    ]

    operations = [
    ]
