# Generated by Django 5.0.6 on 2024-05-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_purchase_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank='True', choices=[('COD', 'Cash on Delivery'), ('COP', 'Cash on Pickup'), ('BT', 'Bank transfer')], max_length=20, null=True),
        ),
    ]
