# Generated by Django 5.0.4 on 2024-06-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_purchaseorder_purchaseorderdetail_delete_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='items',
            field=models.IntegerField(default=0),
        ),
    ]
