# Generated by Django 5.0.6 on 2024-06-02 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customer_barangay_alter_customer_city_and_more'),
        ('store', '0005_alter_delivery_pk_logistics_id'),
        ('transactions', '0007_alter_purchaseorder_total_amount_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='amount_received',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='item',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_value',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='transaction_date',
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='items',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='logistics_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.delivery'),
        ),
        migrations.AddField(
            model_name='sale',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='order_type',
            field=models.CharField(blank=True, choices=[('Online Order', 'Online Order'), ('In-person Transaction', 'In-person Transaction')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Debit Card', 'Debit Card'), ('Bank Transfer', 'Bank Transfer'), ('Gcash', 'Gcash')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='sales_order_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Placed', 'Placed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
