# Generated by Django 5.0.6 on 2024-06-02 20:01

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_remove_sale_amount_received_remove_sale_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='get_customer_name', unique=True),
        ),
    ]
