# Generated by Django 5.0.4 on 2024-06-05 21:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
        ('transactions', '0012_sale_shipping_fee_alter_sale_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='date_issued',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='shipping_fee',
        ),
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.sale'),
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
